374060: Add IP Whitelisting to AFD WAF for Defra Networks and Open VPN
DEFRA/adp-infrastructure-core pull request #193
Opened 2024-06-03 11:53 UTC by santosh-gh

AB#374060

# **What this PR does / why we need it**:
*A brief description of changes being made*
 https://learn.microsoft.com/en-us/azure/virtual-network/service-tags-overview#available-service-tags

# **Special notes for your reviewer**
A new WAF specific to ADP portal is created.
Managed Exclusions and custom rule are added
WAF is associated with FD for ADP Portal

# Testing
*Any relevant testing information and pipeline runs.*
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=574245&view=results
https://dev.azure.com/defragovuk/DEFRA-FFC/_build/results?buildId=574261&view=results

# Checklist (please delete before completing or setting auto-complete)
- [x ] Story Work items associated (not Tasks)
- [x ] Successful testing run(s) link provided
- [x ] Title pattern should be `{work item number}: {title}`
- [x ] Description covers all the changes in the PR
- [ ] This PR contains documentation
- [ ] This PR contains tests

# **How does this PR make you feel**:
![gif]([https://giphy.com/)

2024-06-03 12:53 UTC, kbabigumira requested changes
I can still access the demo service without being on VPN

2024-06-03 16:59 UTC, santosh-gh commented
> I can still access the demo service without being on VPN

Fixed and tested

2024-06-03 19:50 UTC, santosh-gh commented on infra/core/env/front-door/adp-portal/front-door-waf.parameters.json
> +    "customBlockResponseBody": {
Yes , for portal and demo there are different html

2024-06-04 08:54 UTC, kbabigumira approved these changes

2024-06-04 08:56 UTC, ppotturi approved these changes

2024-06-04 09:36 UTC, DaRoszko approved these changes

2024-06-04 13:44 UTC, merged